dist: bionic
language: scala
install:
 - mvn install -DskipTests
script: 
 # test with bouncycastle
 - mvn test -DargLine="-Dfr.acinq.secp256k1.lib.name=foo"
 # test with libsecp256k1
 - mvn test
scala:
- 2.11.11
jdk:
- openjdk11

